# Generated by Django 6.0.8 on 2026-08-24 19:06

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
    ]
